
### Get Index
GET http://localhost:8000/

### Add Account
POST http://localhost:8000/accounts
Content-Type: application/json

{
    "name": "Savings Account",
    "balance": 1000
}

### Get Accounts
GET http://localhost:8000/accounts

### Get Account
GET http://localhost:8000/accounts/7

### Update Account
PUT http://localhost:8000/accounts/3
Content-Type: application/json

{
    "id": 3,
    "name": "Savings Account",
    "balance": 1000,
    "active": false
}

### Delete Account
DELETE http://localhost:8000/accounts/2